package com.styl.pa.enums

import org.junit.Test

class NationalityTest {

    @Test
    fun getNationality() {
        var nationality = Nationality.getNationality("BANGLADESHI")
        assert(nationality == Nationality.BANGLADESHI.value)
        nationality = Nationality.getNationality("BRUNEIAN")
        assert(nationality == Nationality.BRUNEIAN.value)
        nationality = Nationality.getNationality("BURMA")
        assert(nationality == Nationality.BURMA.value)
        nationality = Nationality.getNationality("CAMBODIAN")
        assert(nationality == Nationality.CAMBODIAN.value)
        nationality = Nationality.getNationality("CANADIAN")
        assert(nationality == Nationality.CANADIAN.value)
        nationality = Nationality.getNationality("CHINESE")
        assert(nationality == Nationality.CHINESE.value)
        nationality = Nationality.getNationality("GERMAN")
        assert(nationality == Nationality.GERMAN.value)
        nationality = Nationality.getNationality("HONG KONG")
        assert(nationality == Nationality.HONGKONG.value)
        nationality = Nationality.getNationality("INDONESIAN")
        assert(nationality == Nationality.INDONESIAN.value)
        nationality = Nationality.getNationality("INDIAN")
        assert(nationality == Nationality.INDIAN.value)
        nationality = Nationality.getNationality("JAPANESE")
        assert(nationality == Nationality.JAPANESE.value)
        nationality = Nationality.getNationality("KOREAN, NORTH")
        assert(nationality == Nationality.KOREAN_NORTH.value)
        nationality = Nationality.getNationality("KOREAN, SOUTH")
        assert(nationality == Nationality.KOREAN_SOUTH.value)
        nationality = Nationality.getNationality("LAOTIAN")
        assert(nationality == Nationality.LAOTIAN.value)
        nationality = Nationality.getNationality("SRI LANKAN")
        assert(nationality == Nationality.SRI_LANKAN.value)
        nationality = Nationality.getNationality("MAURITIAN")
        assert(nationality == Nationality.MAURITIAN.value)
        nationality = Nationality.getNationality("MALAYSIAN")
        assert(nationality == Nationality.MALAYSIAN.value)
        nationality = Nationality.getNationality("DUTCH")
        assert(nationality == Nationality.DUTCH.value)
        nationality = Nationality.getNationality("NEW ZEALANDER")
        assert(nationality == Nationality.NEW_ZEALANDER.value)
        nationality = Nationality.getNationality("SINGAPORE CITIZEN")
        assert(nationality == Nationality.SINGAPORE_CITIZEN.value)
        nationality = Nationality.getNationality("SINGAPORE PR")
        assert(nationality == Nationality.SINGAPORE_PR.value)
        nationality = Nationality.getNationality("AMERICAN")
        assert(nationality == Nationality.AMERICAN.value)
        nationality = Nationality.getNationality("AMERICAN SAMOA")
        assert(nationality == Nationality.AMERICAN_SAMOA.value)
        nationality = Nationality.getNationality("AUSTRIAN")
        assert(nationality == Nationality.AUSTRIAN.value)
        nationality = Nationality.getNationality("AUSTRALIAN")
        assert(nationality == Nationality.AUSTRALIAN.value)
        nationality = Nationality.getNationality("FILIPINO")
        assert(nationality == Nationality.FILIPINO.value)
        nationality = Nationality.getNationality("PAKISTANI")
        assert(nationality == Nationality.PAKISTANI.value)
        nationality = Nationality.getNationality("THAI")
        assert(nationality == Nationality.THAI.value)
        nationality = Nationality.getNationality("TAIWANESE")
        assert(nationality == Nationality.TAIWANESE.value)
        nationality = Nationality.getNationality("BRITISH SUBJECT")
        assert(nationality == Nationality.BRITISH_SUBJECT.value)
        nationality = Nationality.getNationality("VIETNAMESE")
        assert(nationality == Nationality.VIETNAMESE.value)
        nationality = Nationality.getNationality("FRANCE")
        assert(nationality == Nationality.FRANCE.value)
        nationality = Nationality.getNationality(null)
        assert(nationality == Nationality.OTHERS)
        nationality = Nationality.getNationality("")
        assert(nationality == Nationality.OTHERS)
    }
}